### ISSUE TITLE
Need autonomous movements based on distance rather than time

### ISSUE THREAD

**Issue by jwalthour** [first95/FRC2017#14]
Our 2017 robot features drivetrain encoders

**Comment by jwalthour** [comment]
It turns out Kovaka has precisely the same configuration of drivetrain encoders.

**Comment by RuggS** [comment]
There are untested versions of distance move and rotate by now uses heading pres

**Comment by jwalthour** [comment]
Kovaka currently lacks speed controllers (yanked for the practice bot).  Thus, this task is currently waiting on:
- Mechanical installation of shaft encoders into the practice robot's drivetrain
- Electrical installation via the adapters we built Saturday
